version: '3'
services:
    testContainer:
        image: test
        container_name: testContainer2
        build: ./
        restart: always
        volumes: 
            - ./work:/tmp/work
        privileged: true
        stdin_open: true
        tty: true
